#!/usr/bin/env node
/**
 * NeuroFlow gallery tool: niivue-qa-page.
 *
 * Reads the NeuroFlow session context and builds a standalone QA web page for a
 * set of NIfTI volumes, using NiiVue's saveHTML/generateHTML extension when the
 * `@niivue/nv-ext-save-html` package is available, and otherwise emitting a
 * self-contained page that loads NiiVue from a CDN. See
 * docs/neuroflow-session-contract.md.
 *
 * Env:
 *   NEUROFLOW_SESSION     session dir with context.json (+ provenance.jsonl)
 *   NEUROFLOW_OUTPUT_DIR  where to write index.html (delivery: index.html)
 *
 * Run standalone for testing:
 *   NEUROFLOW_SESSION=/tmp/sess NEUROFLOW_OUTPUT_DIR=/tmp/sess/outputs/qa \
 *     node generate_qa.mjs
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync, appendFileSync, copyFileSync, readdirSync } from 'node:fs'
import { basename, join } from 'node:path'

const TOOL_ID = 'neuroflow.gallery.tools/niivue-qa-page'
const STEP = process.env.NEUROFLOW_STEP ?? 'qa'

const nowIso = () => new Date().toISOString().replace(/\.\d{3}Z$/, 'Z')

function loadContext() {
  const session = process.env.NEUROFLOW_SESSION
  if (!session) return {}
  const p = join(session, 'context.json')
  return existsSync(p) ? JSON.parse(readFileSync(p, 'utf8')) : {}
}

function outputDir(ctx) {
  const out = process.env.NEUROFLOW_OUTPUT_DIR || ctx.outputDir ||
    join(process.env.NEUROFLOW_SESSION ?? '.', 'outputs', STEP)
  mkdirSync(out, { recursive: true })
  return out
}

function appendProvenance(entry) {
  const session = process.env.NEUROFLOW_SESSION
  if (!session) return
  const line = JSON.stringify({ ts: nowIso(), step: STEP, tool: TOOL_ID, agent: 'niivue-qa-page', ...entry })
  appendFileSync(join(session, 'provenance.jsonl'), line + '\n')
}

/** Resolve the list of volume file paths from context, or discover filtered/*. */
function resolveVolumes(ctx) {
  const inputs = ctx.inputs ?? {}
  let vols = inputs.volumes
  if (Array.isArray(vols) && vols.length) return vols
  // Fall back: discover NIfTI files under the resolved volumes dir or filtered output.
  const dir = inputs.volumesDir || inputs.bids_dir
  if (dir && existsSync(dir)) {
    return readdirSync(dir).filter((f) => f.endsWith('.nii') || f.endsWith('.nii.gz')).map((f) => join(dir, f))
  }
  return []
}

async function tryExtensionHtml(volumeNames, title) {
  // Use the official NiiVue save-html extension if it is installed.
  try {
    const ext = await import('@niivue/nv-ext-save-html')
    const generateHTML = ext.generateHTML ?? ext.default?.generateHTML
    if (typeof generateHTML !== 'function') return null
    // The extension serializes an NVDocument-shaped scene to a standalone page.
    const doc = {
      title,
      imageOptionsArray: volumeNames.map((name) => ({ url: name, name })),
    }
    const html = await generateHTML(doc, { title })
    return typeof html === 'string' ? html : null
  } catch {
    return null // package not installed in this environment — use the CDN fallback
  }
}

function fallbackHtml(volumeNames, title) {
  const list = JSON.stringify(volumeNames.map((name) => ({ url: name, name })))
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${title}</title>
<style>
  body { margin: 0; font-family: system-ui, sans-serif; background: #0b0e14; color: #e6e6e6; }
  header { padding: 12px 16px; border-bottom: 1px solid #222; }
  h1 { font-size: 16px; margin: 0; }
  small { color: #8a94a6; }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(360px, 1fr)); gap: 8px; padding: 8px; }
  .tile { background: #12161f; border: 1px solid #1d2330; border-radius: 8px; overflow: hidden; }
  .tile figcaption { padding: 6px 10px; font-size: 12px; color: #b8c0cf; border-top: 1px solid #1d2330; }
  canvas { width: 100%; height: 320px; display: block; }
</style>
</head>
<body>
<header>
  <h1>${title}</h1>
  <small>Generated by NeuroFlow niivue-qa-page · ${nowIso()}</small>
</header>
<div class="grid" id="grid"></div>
<script type="module">
  import { Niivue } from 'https://esm.sh/@niivue/niivue@0.45.0'
  const volumes = ${list}
  const grid = document.getElementById('grid')
  for (const v of volumes) {
    const fig = document.createElement('figure'); fig.className = 'tile'
    const canvas = document.createElement('canvas')
    const cap = document.createElement('figcaption'); cap.textContent = v.name
    fig.append(canvas, cap); grid.append(fig)
    try {
      const nv = new Niivue({ backColor: [0.04, 0.05, 0.08, 1], show3Dcrosshair: true })
      await nv.attachToCanvas(canvas)
      await nv.loadVolumes([{ url: v.url, name: v.name }])
    } catch (err) {
      cap.textContent = v.name + ' — failed to load (' + err + ')'
    }
  }
</script>
</body>
</html>
`
}

async function main() {
  const ctx = loadContext()
  const title = ctx.inputs?.title ?? 'NeuroFlow QA'
  const out = outputDir(ctx)
  const volumePaths = resolveVolumes(ctx)

  // Copy volumes next to index.html so the page is portable.
  const names = []
  for (const p of volumePaths) {
    const name = basename(p)
    try { copyFileSync(p, join(out, name)); names.push(name) } catch { names.push(p) }
  }

  let html = await tryExtensionHtml(names, title)
  let mode = 'nv-ext-save-html'
  if (!html) { html = fallbackHtml(names, title); mode = 'cdn-fallback' }

  const indexPath = join(out, 'index.html')
  writeFileSync(indexPath, html)
  appendProvenance({ action: 'qa-page', mode, inputCount: names.length, outputs: { qa_html: 'index.html' } })
  console.log(`generate_qa: wrote ${indexPath} [${mode}] with ${names.length} volume(s)`)
}

main().catch((err) => { console.error('generate_qa failed:', err); process.exit(1) })
